version: '3'
services:
  server:
    image: 127.0.0.1:5000/spring-app
    build: .
    ports:
      - 80:8080
    links:
      - postgres
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 3
      labels: [APP=SPRING]
  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=music"
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints: [node.role == manager]
